[build-system]
requires = [
    "setuptools>=61.0",  
    "torch>=2.3.1",
    "gradio==5.7.1",
    "opencv-python==4.10.0.84",
    "ffmpeg-python==0.2.0",

    ]
build-backend = "setuptools.build_meta"
