frames_dir: 'output_frames'
masks_dir: 'output_masks'
combined_dir: 'output_combined'
video_path: 'output_video.mp4'
zip_path: 'output_masks.zip'
tiny:
  sam2_checkpoint: "checkpoints/sam2_hiera_tiny.pt"
  model_cfg: "sam2_hiera_t.yaml"
small:
  sam2_checkpoint: "checkpoints/sam2_hiera_small.pt"
  model_cfg: "sam2_hiera_s.yaml"
base-plus:
  sam2_checkpoint: "checkpoints/sam2_hiera_base_plus.pt"
  model_cfg: "sam2_hiera_b+.yaml"
large:
  sam2_checkpoint: "checkpoints/sam2_hiera_large.pt"
  model_cfg: "sam2_hiera_l.yaml"